/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TacticsIndexRouteImport } from './routes/tactics/index'
import { Route as TacticsCardIdRouteImport } from './routes/tactics/$cardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsIndexRoute = TacticsIndexRouteImport.update({
  id: '/tactics/',
  path: '/tactics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsCardIdRoute = TacticsCardIdRouteImport.update({
  id: '/tactics/$cardId',
  path: '/tactics/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tactics/$cardId': typeof TacticsCardIdRoute
  '/tactics/': typeof TacticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tactics/$cardId': typeof TacticsCardIdRoute
  '/tactics': typeof TacticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tactics/$cardId': typeof TacticsCardIdRoute
  '/tactics/': typeof TacticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tactics/$cardId' | '/tactics/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tactics/$cardId' | '/tactics'
  id: '__root__' | '/' | '/tactics/$cardId' | '/tactics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TacticsCardIdRoute: typeof TacticsCardIdRoute
  TacticsIndexRoute: typeof TacticsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/': {
      id: '/tactics/'
      path: '/tactics'
      fullPath: '/tactics/'
      preLoaderRoute: typeof TacticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/$cardId': {
      id: '/tactics/$cardId'
      path: '/tactics/$cardId'
      fullPath: '/tactics/$cardId'
      preLoaderRoute: typeof TacticsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TacticsCardIdRoute: TacticsCardIdRoute,
  TacticsIndexRoute: TacticsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
